[changelog]
header = """
# ğŸ“¦ Changelog
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7) }}]({{ commit.remote }}{{ commit.id }}))
{% endfor %}
{% endfor %}
"""
footer = ""

[git]
conventional = true
filter_unconventional = true
tag_pattern = "v[0-9]*"
sort_commits = "newest"

[groups]
feat = "âœ¨ Features"
fix = "ğŸ› Fixes"
docs = "ğŸ“ Documentation"
refactor = "ğŸ›  Refactoring"
test = "âœ… Tests"
chore = "ğŸ”§ Chore"
ci = "ğŸ” CI/CD"
style = "ğŸ¨ Style"
perf = "âš¡ Performance"
build = "ğŸ— Build"