[changelog]
header = """
# ğŸ“¦ Changelog
"""
body = """
{% for date, commits in commits | group_by(attribute="date") %}
## {{ date | date(format="%Y-%m-%d") }}

{% for group, inner_commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in inner_commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7) }}](https://github.com/yeongseon/azure-functions-doctor-for-python/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}

{% endfor %}
"""
footer = ""

[git]
conventional = true
filter_unconventional = true
tag_pattern = "v[0-9]*"
sort_commits = "newest"

[groups]
feat = "âœ¨ Features"
fix = "ğŸ› Fixes"
docs = "ğŸ“ Documentation"
refactor = "ğŸ›  Refactoring"
test = "âœ… Tests"
chore = "ğŸ”§ Chore"
ci = "ğŸ” CI/CD"
style = "ğŸ¨ Style"
perf = "âš¡ Performance"
build = "ğŸ— Build"
